{
  "name": "DebbieNodes",
  "website": "",
  "description": "Reliable Node always up. Restaking for the win",
  "logo": "https://images.pexels.com/photos/268533/pexels-photo-268533.jpeg",
  "twitter": ""
}
